
steps:
  - name: "Prepare :mac: 10.12 installer"
    command: .buildkite/prepare.sh "macOS Sierra"
    agents:
      queue: 'packer'

  - wait

  - name: "Build :mac: 10.12 base"
    command: .buildkite/build.sh
    agents:
      queue: 'packer'


