steps:

  - wait
  # - name: ":package: vmkite"
  #   artifact_paths: "output/vmkite-manifest.json"
  #   command: make vmkite
  #   agents:
  #     queue: 'packer'

  - name: ":package: :ubuntu: 16.04"
    command: make ubuntu-16.04
    artifact_paths: "output/ubuntu-manifest.json"
    agents:
      queue: 'packer'

  # - name: ":package: :mac: 10.12"
  #   artifact_paths: "output/mac-manifest.json"
  #   command: make macos-10.12
  #   agents:
  #     queue: 'packer'

  - wait
  - name: ":rocket: upload to scp"
    command: .buildkite/upload-scp.sh
    agents:
      queue: 'packer'

  - name: ":rocket: upload to vsphere"
    command: .buildkite/upload-ovftool.sh
    agents:
      queue: 'packer'
