env:
  OUTPUT_DIR: "/tmp/output/${BUILDKITE_BUILD_ID}"

steps:
  - wait
  - name: ":package: :ubuntu: 16.04"
    command: .buildkite/build.sh ubuntu-16.04
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"

  - name: ":package: :mac: 10.12"
    command: .buildkite/build.sh macos-10.12
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"

  - wait
  - name: ":package: vmkite"
    command: .buildkite/build.sh vmkite ubuntu-16.04
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"

  - name: ":package: :mac: :buildkite: 10.12"
    command: .buildkite/build.sh macos-buildkite-10.12 macos-10.12
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"

  - name: ":package: :ubuntu: :buildkite: 16.04"
    command: .buildkite/build.sh ubuntu-buildkite-16.04 ubuntu-16.04
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"

