steps:

  - name: ":package: :ubuntu: 16.04"
    command: make ubuntu-16.04
    agents:
      queue: 'packer'

  - name: ":package: :mac: 10.12"
    command: make macos-10.12
    agents:
      queue: 'packer'

  # - name: ":package: :mac: 10.11"
  #   command: make macos-10.11
  #   agents:
  #     queue: 'packer'

  # - name: ":package: :mac: 10.10"
  #   command: make macos-10.10
  #   agents:
  #     queue: 'packer'
