steps:

  - name: ":package: :ubuntu: 16.04"
    command: .buildkite/ubuntu.sh
    agents:
      queue: 'packer'

  - name: ":package: :mac: 10.12"
    command: .buildkite/macos.sh "macOS Sierra"
    agents:
      queue: 'packer'

