env:
  OUTPUT_DIR: "/tmp/output/${BUILDKITE_BUILD_ID}"

steps:
  - wait
  - label: ":hammer_and_wrench: :packer: validate"
    command: make validate
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"

  - wait
  - label: ":package: :ubuntu: 16.04"
    command: .buildkite/build.sh ubuntu-16.04
    timeout_in_minutes: 40
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"

  - wait
  - label: ":package: :ubuntu: :buildkite: 16.04"
    command: .buildkite/build.sh ubuntu-buildkite-16.04 ubuntu-16.04
    timeout_in_minutes: 40
    env:
      VSPHERE_UPLOAD: "1"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"

  - label: ":package: vmkite"
    command: .buildkite/build.sh vmkite ubuntu-16.04
    timeout_in_minutes: 40
    env:
      VSPHERE_UPLOAD: "1"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"

  - wait
  - label: ":package: :mac: 10.12"
    command: .buildkite/build.sh macos-10.12
    timeout_in_minutes: 80
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"

  - wait
  - label: ":package: :mac: xcode 10.12"
    command: .buildkite/build.sh macos-xcode-10.12 macos-10.12
    timeout_in_minutes: 80
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"

  - wait
  - label: ":package: :mac: :buildkite: 10.12"
    command: .buildkite/build.sh macos-buildkite-10.12 macos-xcode-10.12
    timeout_in_minutes: 80
    env:
      VSPHERE_UPLOAD: "1"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"

  - wait
  - label: ":package: :windows: 2016"
    command: .buildkite/build.sh windows-2016
    timeout_in_minutes: 120
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"
