#!/bin/bash

set -euo pipefail

echo "~~~ VMKite Stack Information"
cat /etc/vmkite-info

echo "$BUILDKITE_PLUGINS"

export BUILDKITE_PLUGINS='[{"github.com/buildkite-plugins/s3-secrets-buildkite-plugin":{"s3_bucket":"lox-vmkite-test-secrets"}}]'

echo "$BUILDKITE_PLUGINS"