#!/bin/bash
set -euo pipefail

export BUILD_DIR=${BUILD_DIR:-/tmp/vmkite-images}
export HASHES_DIR=${BUILD_DIR}/hashes
export OUTPUT_DIR=${BUILD_DIR}/output
export VMRUN=/Applications/VMware\ Fusion.app/Contents/Library/vmrun

if [[ -d "${OUTPUT_DIR}" ]] ; then
  echo "--- Cleaning up old builds to free up space"
  find "${OUTPUT_DIR}" -type d -mtime +1 -print -exec rm -rf {} \;
  find -L "${HASHES_DIR}" -type l -print -delete
fi

echo "--- Deleting dangling VMs"
for vmx in $("$VMRUN" list | tail -n +2) ; do
  if [[ -f $vmx ]] ; then
    echo "Stopping $vmx"
    "$VMRUN" stop "$vmx"
    echp "Deleting $vmx"
    "$VMRUN" deleteVM "$vmx"
  else
    echo "$vmx is listed as running, but doesn't exist"
    pgrep -f "$vmx"
    echo "Killing process for $vmx"
    pkill -f "$vmx"
  fi
done
