#!/bin/bash

export BUILD_DIR=${BUILD_DIR:-/tmp/vmkite-images}
export HASHES_DIR=${BUILD_DIR}/hashes
export OUTPUT_DIR=${BUILD_DIR}/output/${BUILDKITE_JOB_ID}
export VMRUN=/Applications/VMware\ Fusion.app/Contents/Library/vmrun

echo "--- Deleting old cached builds"
find "${OUTPUT_DIR}" -mtime +1 -exec rm {} \;

echo "--- Deleting broken hashed builds"
find -L "${HASHES_DIR}" -type l -delete

echo "--- Deleting dangling VMs"
for vmx in $("$VMRUN" list | tail -n +2) ; do
  if [[ -f $vmx ]] ; then
    echo "Stopping $vmx"
    "$VMRUN" stop "$vmx"
    echp "Deleting $vmx"
    "$VMRUN" deleteVM "$vmx"
  else
    echo "$vmx is listed as running,  but doesn't exist"
  fi
done