#!/bin/bash
set -euo pipefail

export BUILD_DIR=${BUILD_DIR:-/tmp/vmkite-images}
export HASHES_DIR=${BUILD_DIR}/hashes
export OUTPUT_DIR=${BUILD_DIR}/output
export VMRUN=/Applications/VMware\ Fusion.app/Contents/Library/vmrun

export MIN_FREE_SPACE_GB=30
export MIN_FREE_SPACE_KB=$(( MIN_FREE_SPACE_GB * 1024 * 1024 ))

if [[ $(df -k / | tail -n1 | awk '{print $4}') -lt $MIN_FREE_SPACE_KB ]] && [[ -d "${OUTPUT_DIR}" ]] ; then
  echo "--- Cleaning up old builds to free up space"
  find "${OUTPUT_DIR}" -type d -mtime +1 -print -exec rm -rf {} \;
  find -L "${HASHES_DIR}" -type l -print -delete
fi

for vmx in $("$VMRUN" list | tail -n +2) ; do
  echo "--- Deleting running VM ($vmx)"
  if [[ -f $vmx ]] ; then
    echo "Stopping $vmx"
    "$VMRUN" stop "$vmx"
    echo "Deleting $vmx"
    "$VMRUN" deleteVM "$vmx"
  else
    echo "Listed as running, but doesn't exist"
    pgrep -f "$vmx"
    echo "Killing process for $vmx"
    pkill -f "$vmx"
  fi
done
