#!/bin/bash
set -euo pipefail

if [[ -z $VMKITE_API_HOST ]] ; then
  echo "Missing VMKITE_API_HOST env"
  exit 1
fi

if [[ -z $VMKITE_API_TOKEN ]] ; then
  echo "Missing VMKITE_API_TOKEN env"
  exit 1
fi

if [[ "$OSTYPE" == "darwin"* ]]; then
  if [[ -f ./Brewfile ]] ; then
    echo "~~~ Installing homebrew dependencies"
    brew bundle install
  fi

  if [[ -f ./Podfile ]] ; then
    echo "~~~ Installing cocoapods dependencies"
    pods install --verbose
  fi
fi

if [[ -f Gemfile ]] ; then
  echo "~~~ Installing ruby dependencies with bundler"
  number_of_cores=$(sysctl -n hw.ncpu)
  bundle config --global jobs $((number_of_cores - 1))
  bundler install
fi

echo VMKITE_API_HOST "${VMKITE_API_HOST:-}"
echo VMKITE_API_TOKEN "${VMKITE_API_TOKEN:-}"

curl -X POST "${VMKITE_API_HOST}/notify/hook/pre-command" \
  -H "Authorization: Bearer ${VMKITE_API_TOKEN}"
